# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: as.link_fns.character ----

test_that("as.link_fns.character unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = as.link_fns.character
  

  links <- c("ident", "log", "logit", "probit", "cloglog", "neginv", "inv2")
  test <- seq(0.1, 0.9, 0.1) # within support of all links
  for (l in links) {
    lfn <- as.link_fns(l)
    t <- lfn$trans(test)
    i <- lfn$inv(t)
    testthat::expect_equal(i, test)
  }

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/s3-link_fns-class.R"), c(122, 1, 122+1, 1))
  )
})

# unit test end: as.link_fns.character ----
# unit test start: as.link_fns.numeric ----

test_that("as.link_fns.numeric unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = as.link_fns.numeric
  

  testthat::expect_no_error(withCallingHandlers(
    {
      tmp <- as.link_fns(c(0, 10))
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/s3-link_fns-class.R"), c(224, 1, 224+1, 1))
  )
})

# unit test end: as.link_fns.numeric ----
# end of unit tests ----
