# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: .gg_tiny_theme ----

test_that(".gg_tiny_theme unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .gg_tiny_theme
  

  testthat::expect_no_error(withCallingHandlers(
    {
      ggplot2::ggplot(
        ggplot2::diamonds,
        ggplot2::aes(x = carat, y = price, color = color)
      ) +
        ggplot2::geom_point() +
        .gg_tiny_theme()
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/import-standalone-ggplot-utils.R"), c(171, 1, 171+1, 1))
  )
})

# unit test end: .gg_tiny_theme ----
# end of unit tests ----
