# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: transform ----

test_that("transform unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = transform
  

  t <- transform("log", "norm")
  ps <- seq(0, 1, 0.1)
  qs <- 0:6
  testthat::expect_equal(t$q(ps), qlnorm(ps))
  testthat::expect_equal(t$p(qs), plnorm(qs))
  testthat::expect_equal(t$d(qs), dlnorm(qs))
  
  t2 <- transform("log", "norm", 0.4, 0.1)
  testthat::expect_equal(t2$q(ps), qlnorm(ps, 0.4, 0.1))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/dist-transform.R"), c(36, 1, 36+1, 1))
  )
})

# unit test end: transform ----
# end of unit tests ----
