# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: calculate_rmse ----

test_that("calculate_rmse unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = calculate_rmse
  

  # zero if no distance
  testthat::expect_equal(calculate_rmse(0:10, 0:10), 0)
  
  testthat::expect_equal(
    calculate_rmse(rep(5, 11), 0:10),
    3.16227766016838
  )
  
  withr::with_seed(100, {
    ref <- rnorm(1000)
    cmp1 <- rnorm(1000)
    cmp2 <- rnorm(1000, sd = 2)
  })
  
  breaks <- seq(-2, 2, length.out = 8)
  nref <- table(cut(ref, breaks))
  ncmp1 <- table(cut(cmp1, breaks))
  ncmp2 <- table(cut(cmp2, breaks))
  
  tmp1 <- calculate_rmse(ncmp1, nref)
  tmp2 <- calculate_rmse(ncmp2, nref)
  
  testthat::expect_equal(tmp1, 10.3578817470424)
  testthat::expect_equal(tmp2, 68.8403951179829)

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/calculate-rmse.R"), c(16, 1, 16+1, 1))
  )
})

# unit test end: calculate_rmse ----
# end of unit tests ----
