# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: truncate ----

test_that("truncate unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = truncate
  

  shape2_gamma <- as.dist_fns(pgamma, shape = 2)
  g2 <- truncate(shape2_gamma, 0.5, 4)
  
  testthat::expect_equal(
    format(g2),
    "trunc(gamma(shape = 2, rate = 1), 0.50 - 4.00); Median (IQR) 1.68 [1.08 — 2.46]"
  )
  
  testthat::expect_equal(
    g2$p(0:5),
    c(0, 0.212702667019627, 0.615716430100344, 0.868531239886668, 1, 1)
  )
  
  testthat::expect_equal(g2$q(seq(0, 1, 0.2)), c(
    0.5,
    0.971743593113941,
    1.42711359317907,
    1.95304152540128,
    2.6642447272259,
    4
  ))
  
  
  g3 <- truncate(shape2_gamma, NA, 4)
  testthat::expect_equal(
    format(g3),
    "trunc(gamma(shape = 2, rate = 1), 0.00 - 4.00); Median (IQR) 1.54 [0.899 — 2.35]"
  )
  
  g4 <- truncate(shape2_gamma, 2, NA)
  testthat::expect_equal(
    format(g4),
    "trunc(gamma(shape = 2, rate = 1), 2.00 - Inf); Median (IQR) 2.97 [2.42 — 3.87]"
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/dist-truncated.R"), c(34, 1, 34+1, 1))
  )
})

# unit test end: truncate ----
# end of unit tests ----
