# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: .p_from_n ----

test_that(".p_from_n unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .p_from_n
  

  testthat::expect_equal(
    .p_from_n(c(0, 5, 100), 5, 100),
    c(1, 0.5, 0.01)
  )
  
  testthat::expect_error(
    {
      .p_from_n(0, 50, 1)
    },
    "inconsistent parameters, n_01 must be larger than n_50.",
    fixed = TRUE
  )
  
  testthat::expect_equal(.p_from_n(c(0:10), 5, 10, 0.1), c(
    0.1,
    0.0999976758268449,
    0.0997704297474442,
    0.0967278219151741,
    0.081446655140766,
    0.05,
    0.0229935645768342,
    0.0097036542590398,
    0.00424593238101868,
    0.00199056073397113,
    0.001
  ))
  
  # does not go below
  testthat::expect_equal(
    .p_from_n(c(1000, 10000, 100000), 5, 50),
    c(5e-04, 5e-05, 5e-06)
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/standalone-sigmoid.R"), c(40, 1, 40+1, 1))
  )
})

# unit test end: .p_from_n ----
# unit test start: .p_from_n2 ----

test_that(".p_from_n2 unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .p_from_n2
  

  testthat::expect_equal(.p_from_n2(0:5, 1), c(
    1,
    0.707106781186547,
    0.447213595499958,
    0.316227766016838,
    0.242535625036333,
    0.196116135138184
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/standalone-sigmoid.R"), c(93, 1, 93+1, 1))
  )
})

# unit test end: .p_from_n2 ----
# unit test start: scale_probability ----

test_that("scale_probability unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = scale_probability
  

  testthat::expect_no_error(withCallingHandlers(
    {
      scale_probability(0.5, c(0.25, 0.5, 1, 2, 4))
    },
    warning = function(e) {
      message("Warning issued: ", e$message)
      invokeRestart("muffleWarning")
    }
  ))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/standalone-sigmoid.R"), c(124, 1, 124+1, 1))
  )
})

# unit test end: scale_probability ----
# end of unit tests ----
