# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: .recycle ----

test_that(".recycle unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .recycle
  

  testfn <- function(a, b, c) {
    n <- .recycle(a, b, c)
    return(list(
      a = a,
      b = b,
      c = c,
      n = n
    ))
  }
  
  tmp <- testfn(a = c(1, 2, 3), b = "needs recycling", c = NULL)
  
  testthat::expect_equal(tmp$n, 3)
  testthat::expect_null(tmp$c)
  testthat::expect_equal(length(tmp$a), length(tmp$b))
  
  # no parameter
  testthat::expect_error(testfn(a = c(1, 2, 3), c = NULL))
  
  tmp <- testfn(a = character(), b = integer(), c = NULL)
  
  testthat::expect_equal(tmp$n, 0)
  
  # inconsistent to have a zero length and a non zero length
  testthat::expect_error(testfn(a = c("a", "b"), b = integer(), c = NULL))
  
  # This is currently unsupported
  # testfn = function(a, b, c, ...) {
  # n = .recycle(a,b,c, ...)
  # return(list(
  #   a=a, b=b, c=c, n=n, ...
  # ))
  # }
  #
  # tmp = testfn(a=c(1,2,3), b="needs recycling", c=NULL, d="additional")

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/import-standalone-recycle.R"), c(34, 1, 34+1, 1))
  )
})

# unit test end: .recycle ----
# unit test start: .make_square ----

test_that(".make_square unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .make_square
  

  lst <- list(a = 1, b = 1:3, c = NULL, d = list(), e = character())
  testthat::expect_equal(
    .make_square(lst),
    list(a = c(1, 1, 1), b = 1:3)
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/import-standalone-recycle.R"), c(144, 1, 144+1, 1))
  )
})

# unit test end: .make_square ----
# end of unit tests ----
