# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: .log_q_proposal_vectorized ----

test_that(".log_q_proposal_vectorized unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .log_q_proposal_vectorized
  

  # Previous particles: 100 samples from N(0, 1)
  N_prev <- 100
  theta_prev <- matrix(rnorm(N_prev, 0, 1), ncol = 1)
  w_prev <- rep(1 / N_prev, N_prev) # uniform weights
  Sigma_pert <- matrix(0.5^2, nrow = 1, ncol = 1) # scalar variance
  
  # New point
  theta_new <- matrix(c(0.5), ncol = 1)
  
  # Compute via vectorized function
  q_val_fast <- .log_q_proposal_vectorized(theta_new, theta_prev, w_prev, Sigma_pert)
  
  # Compute via slow loop (ground truth)
  q_val_slow <- 0
  for (j in 1:N_prev) {
    q_val_slow <- q_val_slow + w_prev[j] * dnorm(theta_new, mean = theta_prev[j], sd = sqrt(Sigma_pert))
  }
  expect_equal(exp(q_val_fast), as.vector(q_val_slow))

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/utils-abc.R"), c(734, 1, 734+1, 1))
  )
})

# unit test end: .log_q_proposal_vectorized ----
# end of unit tests ----
