# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: mixture ----

test_that("mixture unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = mixture
  

  dists <- c(
    as.dist_fns("norm", mean = -1),
    as.dist_fns("norm", mean = 1),
    as.dist_fns("gamma", shape = 2)
  )
  weights <- c(1, 1, 0.3)
  
  mix <- mixture(dists, weights)
  testthat::expect_equal(
    format(mix),
    "mixture; Median (IQR) 0.289 [-0.886 — 1.31]"
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/dist-mixture.R"), c(14, 1, 14+1, 1))
  )
})

# unit test end: mixture ----
# end of unit tests ----
