# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: .autocrate ----

test_that(".autocrate unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .autocrate
  

  z <- 13
  tmp <- .autocrate(function(x) {
    y <- runif(x)
    stats::rnorm(x, y)
    x[1] <- 12
    x[2] <- !!z # inlining happens during expression parsing...?
  })
  
  # unqualified reference is qualified
  testthat::expect_equal(format(body(tmp)), c(
    "{",
    "    y <- stats::runif(x)",
    "    stats::rnorm(x, y)",
    "    x[1] <- 12",
    "    x[2] <- 13",
    "}"
  ))
  
  tmpfn <- function(x) {
    "temp"
  }
  tmpvar <- 10
  
  testthat::expect_error(
    {
      .autocrate(function(y) {
        if (tmpvar == 10) tmpfn(y)
      })
    },
    "References to undefined globals in function: tmpvar,tmpfn",
    fixed = TRUE
  )
  
  with_ref <- .autocrate(
    function(y) {
      if (tmpvar == 10) tmpfn(y)
    },
    tmpvar = tmpvar,
    tmpfn = tmpfn
  )
  
  testthat::expect_equal(
    ls(rlang::fn_env(with_ref)),
    c("tmpfn", "tmpvar")
  )
  
  library(dplyr)
  # Global definitions in dplyr must be explicitly assigned like in .
  a <- .autocrate(function(x) {
    Species <- NULL
    x %>%
      pull(Species) %>%
      head(5)
  })
  
  testthat::expect_equal(a(iris), structure(
    c(1L, 1L, 1L, 1L, 1L),
    levels = c("setosa", "versicolor", "virginica"),
    class = "factor"
  ))
  
  # Autocrating is recursive on functions supplied as globals:
  not_crated_fn <- function(x) {
    rnorm(x)
    return("success")
  }
  
  crated_fn <- .autocrate(function(x) {
    generator(x)
  }, generator = not_crated_fn)
  
  tmp <- format(body(rlang::fn_env(crated_fn)$generator))
  
  testthat::expect_equal(
    tmp,
    c("{", "    stats::rnorm(x)", "    return(\"success\")", "}")
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/utils-crate.R"), c(12, 1, 12+1, 1))
  )
})

# unit test end: .autocrate ----
# end of unit tests ----
