# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: empirical ----

test_that("empirical unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = empirical
  

  # from cdf:
  xs <- c(2, 3, 6, 9)
  ps <- c(0.1, 0.4, 0.6, 0.95)
  e <- empirical(xs, ps, link = "log")
  
  testthat::expect_equal(e$p(xs), ps)
  testthat::expect_equal(e$q(ps), xs)
  
  # from samples:
  withr::with_seed(123, {
    e2 <- empirical(rnorm(10000), knots = 20)
    testthat::expect_equal(e2$p(-5:5), pnorm(-5:5), tolerance = 0.01)
    testthat::expect_equal(
      e2$q(seq(0, 1, 0.1)),
      qnorm(seq(0, 1, 0.1)),
      tolerance = 0.025
    )
  })
  
  p2 <- seq(0, 1, 0.1)
  testthat::expect_equal(e2$p(e2$q(p2)), p2, tolerance = 0.001)
  
  # quantiles:
  p <- c(0.025, 0.05, 0.10, 0.25, 0.5, 0.75, 0.9, 0.95, 0.975)
  q <- stats::qgamma(p, shape = 2)
  shape2_gamma <- as.dist_fns(pgamma, shape = 2)
  gemp <- empirical(q, p, link = shape2_gamma)
  withr::with_seed(
    123,
    {
      testthat::expect_equal(mean(gemp$r(100000)), 2, tolerance = 0.01)
      testthat::expect_equal(sd(gemp$r(100000)), sqrt(2), tolerance = 0.01)
    }
  )
  
  # With perfect input can recover the underlying distribution including tails:
  tmp <- empirical(
    x = seq(0.01, 0.99, 0.01),
    link = as.dist_fns(punif, 0, 1),
    knots = 100
  )
  testthat::expect_equal(
    tmp$q(c(0.01, 0.1, 0.25, 0.75, 0.9, 0.99)),
    c(0.01, 0.1, 0.25, 0.75, 0.9, 0.99),
    tolerance = 0.002
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/dist-empirical.R"), c(49, 1, 49+1, 1))
  )
})

# unit test end: empirical ----
# end of unit tests ----
