# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(tidyabc)

# unit test start: new_abc_prior ----

test_that("new_abc_prior unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = new_abc_prior
  

  p <- new_abc_prior(
    .dists = list(
      mean = as.dist_fns("norm", 4, 2),
      sd = as.dist_fns("gamma", 2)
    ),
    .derived = list(
      shape ~ mean^2 / sd^2,
      rate ~ mean / sd^2
    ),
    .constraints = list(
      ~ mean > sd
    )
  )
  
  testthat::expect_equal(
    format(p),
    "Parameters: \n* mean: norm(mean = 4, sd = 2)\n* sd: gamma(shape = 2, rate = 1)\nConstraints:\n* mean > sd\nDerived values:\n* shape = mean^2/sd^2\n* rate = mean/sd^2"
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/s3-abc_prior-class.R"), c(125, 1, 125+1, 1))
  )
})

# unit test end: new_abc_prior ----
# unit test start: .sample_priors ----

test_that(".sample_priors unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .sample_priors
  

  p <- new_abc_prior(
    .dists = list(
      mean = as.dist_fns("norm", 4, 2),
      sd = as.dist_fns("gamma", 2)
    ),
    .derived = list(
      shape ~ mean^2 / sd^2,
      rate ~ mean / sd^2
    )
  )
  
  s <- .sample_priors(p, 10)
  testthat::expect_equal(
    colnames(s),
    c("abc_mvn_mean", "mean", "abc_mvn_sd", "sd")
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/s3-abc_prior-class.R"), c(199, 1, 199+1, 1))
  )
})

# unit test end: .sample_priors ----
# unit test start: .sample_constrained ----

test_that(".sample_constrained unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = .sample_constrained
  

  p <- new_abc_prior(
    .dists = list(
      mean = as.dist_fns("norm", 4, 2),
      sd = as.dist_fns("gamma", 2)
    ),
    .derived = list(
      shape ~ mean^2 / sd^2,
      rate ~ mean / sd^2
    ),
    .constraints = list(
      ~ mean > sd
    )
  )
  
  s <- .sample_constrained(p, 1000)
  
  testthat::expect_equal(
    colnames(s),
    c("abc_mvn_mean", "mean", "abc_mvn_sd", "sd", "shape", "rate")
  )
  
  testthat::expect_equal(all(s$mean > s$sd), TRUE)

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/s3-abc_prior-class.R"), c(256, 1, 256+1, 1))
  )
})

# unit test end: .sample_constrained ----
# end of unit tests ----
